name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained
    - name: Zip
      run: zip analog-linux-x64 /home/runner/work/analog/analog/src/Analog.Cli/bin/Release/net8.0/linux-x64/publish/*
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: analog-linux-x64
        path: analog-linux-x64
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained
    - name: Zip
      shell: pwsh
      run: Compress-Archive -Path D:\a\analog\analog\src\Analog.Cli\bin\Release\net8.0\win-x64\publish\* -DestinationPath analog-win-x64.zip
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: analog-win-x64
        path: analog-win-x64.zip
  macos-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained
    - name: Zip
      run: zip analog-osx-x64 /Users/runner/work/analog/analog/src/Analog.Cli/bin/Release/net8.0/osx-x64/publish/*
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: analog-osx-x64
        path: analog-osx-x64
