name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained  
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore --configuration Release 
    - name: Test
      run: dotnet test src --no-build --configuration Release --verbosity normal
    - name: Publish
      run: dotnet publish src/Analog.Cli --configuration Release --self-contained
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
